version: "2.2"

services:
      # docker container exec -it pg-jarvis-test bash -c 'PGPASSWORD=mamadspass psql -U mamad -h 50.0.0.10 mamad_db'
      pg-jarvis-test:
            image: postgres:15.4
            container_name: pg-jarvis-test
            restart: always
            expose:
                  - 5432
            environment:
                  - POSTGRES_USER=mamad
                  - POSTGRES_PASSWORD=mamadspass
                  - POSTGRES_DB=mamad_db
            # networks:
            #       service_dependency_net:
            #             ipv4_address: 50.0.0.10
            ports:
                  - "5432:5432"
            volumes:
                  - /dev/shm/pg-jarvis-test:/var/lib/postgresql/data
            healthcheck:
                  test: ["CMD-SHELL", "sh -c 'pg_isready -U mamad -d mamad_db'"]
                  interval: 10s
                  timeout: 3s
                  retries: 3
# networks:
#       service_dependency_net:
#             driver: bridge
#             name: pg_jarvis_dependency_net
#             ipam:
#                   config:
#                         - subnet: 50.0.0.0/24
